image: ubuntu:latest

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip wget mongodb
  - pip3 install -r reqs.txt
#  - wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
#  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
#  - apt-get install -y mongodb-org

run-test:
  script: 
    - cd mysite
    - python3 manage.py test
