image: ubuntu:latest

services: 
  - name: mongo:latest
    alias: localhost

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip wget mongodb
  - pip3 install -r reqs.txt

run-test:
  script: 
    - cd mysite
    - python3 manage.py test
