stages:
  - test
  - upload

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:LATEST
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

# alias is set to localhost since gitlab runner runs the database in a separate container and
# in the settings.py file of the django project it is defined that the database is on the same
# host. so the database is renamed to localhost:27017, which is the default port, for the 
# network adress from the usual mongo:27017
test:
  stage: test
  image: ubuntu:latest

  services: 
    - name: mongo:latest
    
  before_script:
    - apt-get update -qy
    - apt-get install -y python3 python3-pip wget mongodb
    - pip3 install -r reqs.txt
  script: 
    - cd mysite
    - python3 manage.py test


upload:
  stage: upload
  image: docker:latest
  services:
    - docker:dind

  before_script:
    - docker network create mynet

  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST --network mynet .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST