before_script:
  - apt-get update
  - apt-get -y install python3-pip
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
  - pip3 install djongo
  - apt-get install -y mongodb-org

run-test:
  script: 
    - python3 manage.py runserver
