# Service for the k8s deployment specifying the necessary ports.
apiVersion: v1
kind: Service
metadata:
  name: ml-service
  labels:
    app: ml-front
spec:
  type: NodePort
  selector:
    app: ml-front
  ports:
    - nodePort: 32300
      port: 80
      targetPort: 80