# Generated by Django 3.0.5 on 2020-09-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangaentry',
            name='name',
            field=models.CharField(default='Placeholder', max_length=200),
        ),
    ]
